name: Test

on:
  workflow_dispatch:
    inputs:
      versioning_level:
        type: choice
        required: true
        description: level
        options: 
        - major
        - minor
        - patch
      message:
        required: true

jobs:
  branch_name:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: describe
        run: |
          echo "::set-output name=all::$(git describe --tags)"
          echo "::set-output name=latest_tag::$(git describe --abbrev=0 --tags)"

      - name: Is major
        if: github.event.inputs.versioning_level == 'major'
        run: |
          echo "${{ steps.describe.outputs.all }}"
          echo "${{ steps.describe.outputs.latest_tag }}"
          echo "${{ github.event.inputs.message }}"

      - name: Is minor
        if: github.event.inputs.versioning_level == 'minor'
        run: |
          echo "${{ steps.describe.outputs.all }}"
          echo "${{ steps.describe.outputs.latest_tag }}"
          echo "${{ github.event.inputs.message }}"

      - name: Is patch
        if: github.event.inputs.versioning_level == 'patch'
        run: |
          echo "${{ steps.describe.outputs.all }}"
          echo "${{ steps.describe.outputs.latest_tag }}"
          echo "${{ github.event.inputs.message }}"

#      - run: |
#          gh pr list --label "Production Release" | grep "develop" \
#            || gh pr create --base master --title "本番反映" --body "**マージすると本番にリリースされます。**" --label "Production Release"
#