name: Test

on:
  workflow_dispatch:
    inputs:
      versioning_level:
        type: choice
        required: true
        description: level
        options: 
        - major
        - minor
        - patch
      message:
        required: true

jobs:
  branch_name:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: describe
        run: |
          echo "::set-output name=all::$(git describe --tags)"
          echo "::set-output name=latest_tag::$(git describe --abbrev=0 --tags)"

      - id: latest_version
        shell: bash
        env:
          latest_tag: steps.describe.outputs.latest_tag
        run: |
          if [[ $latest_tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::set-output name=major::$(echo $latest_tag | sed -r 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1/')"
            echo "::set-output name=minor::$(echo $latest_tag | sed -r 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\2/')"
            echo "::set-output name=patch::$(echo $latest_tag | sed -r 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\3/')"
          else
            return 1
          fi
      - name: Is major
        if: github.event.inputs.versioning_level == 'major'
        shell: bash
        env:
          mejor: ${{ steps.latest_version.outputs.major }}
          minor: ${{ steps.latest_version.outputs.minor }}
          patch: ${{ steps.latest_version.outputs.patch }}
        run: |
          echo "v$((${major}+1)).0.0"
          echo "${{ github.event.inputs.message }}"

      - name: Is minor
        if: github.event.inputs.versioning_level == 'minor'
        shell: bash
        env:
          mejor: ${{ steps.latest_version.outputs.major }}
          minor: ${{ steps.latest_version.outputs.minor }}
          patch: ${{ steps.latest_version.outputs.patch }}
        run: |
          echo "v${major}.$((${minor}+1)).0"
          echo "${{ github.event.inputs.message }}"

      - name: Is patch
        if: github.event.inputs.versioning_level == 'patch'
        shell: bash
        env:
          mejor: ${{ steps.latest_version.outputs.major }}
          minor: ${{ steps.latest_version.outputs.minor }}
          patch: ${{ steps.latest_version.outputs.patch }}
        run: |
          echo "v${major}.${minor}.$((${patch}+1))"
          echo "${{ github.event.inputs.message }}"

#      - run: |
#          gh pr list --label "Production Release" | grep "develop" \
#            || gh pr create --base master --title "本番反映" --body "**マージすると本番にリリースされます。**" --label "Production Release"
#